services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - network

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - network

  tweets-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tweets-service
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgresdata:
