server:
  port: ":8080"
db:
  redis:
    addr: "redis:6379"
    password: ""
    db: 0
  postgres:
    dsn: "host=postgres user=admin password=admin123 dbname=db port=5432 sslmode=disable"

env: "development"